// <auto-generated />
using System;
using DoAnCoSo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCoSo.Migrations
{
    [DbContext(typeof(QLKTXDbContext))]
    [Migration("20251207081034_database_01")]
    partial class database_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCoSo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiTietThietBi", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaThietBi")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhong", "MaThietBi");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ChiTietThietBis");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVu");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            MaChucVu = "1",
                            TenChucVu = "Nhân viên Kế toán"
                        },
                        new
                        {
                            MaChucVu = "2",
                            TenChucVu = "Bảo vệ"
                        },
                        new
                        {
                            MaChucVu = "3",
                            TenChucVu = "Thu ngân"
                        });
                });

            modelBuilder.Entity("DoAnCoSo.Models.DangKyDichVu", b =>
                {
                    b.Property<string>("MaDKDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDKDV");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKyDichVus");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DangKyO", b =>
                {
                    b.Property<string>("MaDK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhong")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayBatDauO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThucO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDK");

                    b.HasIndex("MaPhong");

                    b.HasIndex("UserId");

                    b.ToTable("DangKyOs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DichVu", b =>
                {
                    b.Property<string>("MaDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DienNuoc", b =>
                {
                    b.Property<string>("MaDN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGiaDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoDien")
                        .HasColumnType("int");

                    b.Property<int>("SoNuoc")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDN");

                    b.HasIndex("MaPhong");

                    b.ToTable("DienNuocs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HinhAnhPhong", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("LoaiHinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhong")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaPhong");

                    b.ToTable("HinhAnhPhongs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiChiPhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDKDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDN")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDKDV")
                        .IsUnique()
                        .HasFilter("[MaDKDV] IS NOT NULL");

                    b.HasIndex("MaDN")
                        .IsUnique()
                        .HasFilter("[MaDN] IS NOT NULL");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaSV");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHoaDon"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HopDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaSV");

                    b.HasIndex("NhanVienMaNV");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LichTrucNhanVien", b =>
                {
                    b.Property<string>("MaLT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CaTruc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTruc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLT");

                    b.HasIndex("MaNV");

                    b.ToTable("LichTrucNhanViens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChucVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NoiQuy", b =>
                {
                    b.Property<string>("MaNoiQuy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MucPhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNoiQuy");

                    b.ToTable("NoiQuys");

                    b.HasData(
                        new
                        {
                            MaNoiQuy = "NQ01",
                            MucPhat = "200.000 VNĐ",
                            NoiDung = "Không hút thuốc trong ký túc xá"
                        },
                        new
                        {
                            MaNoiQuy = "NQ02",
                            MucPhat = "150.000 VNĐ",
                            NoiDung = "Không gây ồn ào sau 22h"
                        },
                        new
                        {
                            MaNoiQuy = "NQ03",
                            MucPhat = "300.000 VNĐ",
                            NoiDung = "Không nuôi động vật trong phòng"
                        },
                        new
                        {
                            MaNoiQuy = "NQ04",
                            MucPhat = "250.000 VNĐ",
                            NoiDung = "Không tự ý thay đổi thiết bị trong phòng"
                        },
                        new
                        {
                            MaNoiQuy = "NQ05",
                            MucPhat = "500.000 VNĐ",
                            NoiDung = "Không mang chất cháy nổ vào ký túc xá"
                        },
                        new
                        {
                            MaNoiQuy = "NQ06",
                            MucPhat = "100.000 VNĐ",
                            NoiDung = "Không xả rác bừa bãi"
                        },
                        new
                        {
                            MaNoiQuy = "NQ07",
                            MucPhat = "200.000 VNĐ",
                            NoiDung = "Không tổ chức tiệc trong phòng"
                        });
                });

            modelBuilder.Entity("DoAnCoSo.Models.PhanHoi", b =>
                {
                    b.Property<string>("MaPhanHoi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTinNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinhVienMaSV")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaPhanHoi");

                    b.HasIndex("SinhVienMaSV");

                    b.ToTable("PhanHois");
                });

            modelBuilder.Entity("DoAnCoSo.Models.PhieuDuyet", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaDK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaQTV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaDK")
                        .IsUnique();

                    b.HasIndex("MaQTV");

                    b.ToTable("PhieuDuyets");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaToaID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoGiuong")
                        .HasColumnType("int");

                    b.Property<int>("SoSinhVienHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SoSinhVienToiDa")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaToaID");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.QuanTriVien", b =>
                {
                    b.Property<string>("MaQTV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("MaQTV");

                    b.ToTable("QuanTriViens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhapKTX")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SuCoBaoTri", b =>
                {
                    b.Property<string>("MaSuCo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaThietBi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayPhatHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSuCo");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaThietBi");

                    b.ToTable("SuCoBaoTris");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SuKien", b =>
                {
                    b.Property<string>("MaSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaQTV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayToChuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSuKien");

                    b.HasIndex("MaQTV");

                    b.ToTable("SuKiens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThietBi", b =>
                {
                    b.Property<string>("MaThietBi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThietBi");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThongBao", b =>
                {
                    b.Property<string>("MaTB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaQTV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTB");

                    b.HasIndex("MaQTV");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Toa", b =>
                {
                    b.Property<string>("MaToa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiSuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoTang")
                        .HasColumnType("int");

                    b.Property<string>("TenToa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaToa");

                    b.ToTable("Toas");

                    b.HasData(
                        new
                        {
                            MaToa = "A",
                            DiaChi = "Khu A",
                            LoaiSuDung = "Ký túc xá",
                            SoTang = 5,
                            TenToa = "Tòa A"
                        },
                        new
                        {
                            MaToa = "B",
                            DiaChi = "Khu B",
                            LoaiSuDung = "Ký túc xá",
                            SoTang = 4,
                            TenToa = "Tòa B"
                        },
                        new
                        {
                            MaToa = "C",
                            DiaChi = "Khu C",
                            LoaiSuDung = "Ký túc xá",
                            SoTang = 6,
                            TenToa = "Tòa C"
                        },
                        new
                        {
                            MaToa = "D",
                            DiaChi = "Khu D",
                            LoaiSuDung = "Ký túc xá",
                            SoTang = 3,
                            TenToa = "Tòa D"
                        },
                        new
                        {
                            MaToa = "E",
                            DiaChi = "Khu E",
                            LoaiSuDung = "Ký túc xá",
                            SoTang = 7,
                            TenToa = "Tòa E"
                        });
                });

            modelBuilder.Entity("DoAnCoSo.Models.ViPham", b =>
                {
                    b.Property<string>("MaViPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNoiQuy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayViPham")
                        .HasColumnType("datetime2");

                    b.HasKey("MaViPham");

                    b.HasIndex("MaNoiQuy");

                    b.HasIndex("MaSV");

                    b.ToTable("ViPhams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiTietThietBi", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany("ChiTietThietBis")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.ThietBi", "ThietBi")
                        .WithMany("ChiTietThietBis")
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChucVu", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DangKyDichVu", b =>
                {
                    b.HasOne("DoAnCoSo.Models.DichVu", "DichVu")
                        .WithMany("DangKyDichVus")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DoAnCoSo.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyDichVus")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DichVu");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DangKyO", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany("DangKyOs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DoAnCoSo.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Phong");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DienNuoc", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany("DienNuocs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HinhAnhPhong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany("HinhAnhPhong")
                        .HasForeignKey("MaPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.HasOne("DoAnCoSo.Models.DangKyDichVu", "DangKyDichVu")
                        .WithOne("HoaDon")
                        .HasForeignKey("DoAnCoSo.Models.HoaDon", "MaDKDV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DoAnCoSo.Models.DienNuoc", "DienNuoc")
                        .WithOne("HoaDon")
                        .HasForeignKey("DoAnCoSo.Models.HoaDon", "MaDN");

                    b.HasOne("DoAnCoSo.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DoAnCoSo.Models.SinhVien", "SinhVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaSV");

                    b.Navigation("DangKyDichVu");

                    b.Navigation("DienNuoc");

                    b.Navigation("NhanVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DoAnCoSo.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HopDong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.SinhVien", "SinhVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.NhanVien", null)
                        .WithMany("HopDongs")
                        .HasForeignKey("NhanVienMaNV");

                    b.Navigation("NhanVien");

                    b.Navigation("Phong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LichTrucNhanVien", b =>
                {
                    b.HasOne("DoAnCoSo.Models.NhanVien", "NhanVien")
                        .WithMany("LichTrucs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NhanVien", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ChucVu", "chucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("DoAnCoSo.Models.PhanHoi", b =>
                {
                    b.HasOne("DoAnCoSo.Models.SinhVien", null)
                        .WithMany("PhanHois")
                        .HasForeignKey("SinhVienMaSV");
                });

            modelBuilder.Entity("DoAnCoSo.Models.PhieuDuyet", b =>
                {
                    b.HasOne("DoAnCoSo.Models.DangKyO", "DangKyO")
                        .WithOne()
                        .HasForeignKey("DoAnCoSo.Models.PhieuDuyet", "MaDK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.QuanTriVien", "QuanTriVien")
                        .WithMany("PhieuDuyets")
                        .HasForeignKey("MaQTV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DangKyO");

                    b.Navigation("QuanTriVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Phong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Toa", "Toa")
                        .WithMany("Phongs")
                        .HasForeignKey("MaToaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Toa");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SuCoBaoTri", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany("SuCoBaoTris")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.ThietBi", "ThietBi")
                        .WithMany("SuCoBaoTris")
                        .HasForeignKey("MaThietBi");

                    b.Navigation("Phong");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SuKien", b =>
                {
                    b.HasOne("DoAnCoSo.Models.QuanTriVien", "QuanTriVien")
                        .WithMany("SuKiens")
                        .HasForeignKey("MaQTV");

                    b.Navigation("QuanTriVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThongBao", b =>
                {
                    b.HasOne("DoAnCoSo.Models.QuanTriVien", "QuanTriVien")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaQTV");

                    b.Navigation("QuanTriVien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ViPham", b =>
                {
                    b.HasOne("DoAnCoSo.Models.NoiQuy", "NoiQuy")
                        .WithMany("ViPhams")
                        .HasForeignKey("MaNoiQuy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.SinhVien", "SinhVien")
                        .WithMany("ViPhams")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoiQuy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DangKyDichVu", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DichVu", b =>
                {
                    b.Navigation("DangKyDichVus");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DienNuoc", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HopDongs");

                    b.Navigation("LichTrucs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NoiQuy", b =>
                {
                    b.Navigation("ViPhams");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Phong", b =>
                {
                    b.Navigation("ChiTietThietBis");

                    b.Navigation("DangKyOs");

                    b.Navigation("DienNuocs");

                    b.Navigation("HinhAnhPhong");

                    b.Navigation("HopDongs");

                    b.Navigation("SuCoBaoTris");
                });

            modelBuilder.Entity("DoAnCoSo.Models.QuanTriVien", b =>
                {
                    b.Navigation("PhieuDuyets");

                    b.Navigation("SuKiens");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyDichVus");

                    b.Navigation("HoaDons");

                    b.Navigation("HopDongs");

                    b.Navigation("PhanHois");

                    b.Navigation("ViPhams");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThietBi", b =>
                {
                    b.Navigation("ChiTietThietBis");

                    b.Navigation("SuCoBaoTris");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Toa", b =>
                {
                    b.Navigation("Phongs");
                });
#pragma warning restore 612, 618
        }
    }
}
